-- Script Date: 4/8/2018 2:02 PM  - ErikEJ.SqlCeScripting version 3.5.2.75
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (1,'PLCS','Pritikin Longevity Center + Spa','Miami, FL','More than 100,000 guests worldwide have visited the Pritikin Longevity Center and Spa in Miami, both to prevent and reverse problems such as excess weight, heart disease, diabetes, high blood pressure, high cholesterol and cancer risk factors. Certified physicians provide each guest with the expert medical attention required for achieving major life changes, while faculty --leaders in the fields of medicine, nutrition, psychology and exercise � lead eye-opening classes focused on subjects including dining out, reading labels and calorie density',6,NULL,NULL,NULL,NULL,1,0,0,0,1,1,0,0,0,0,69,499,1,'http://www.10best.com/awards/travel/best-health-wellness-resort-2016/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (2,'OAO','The Oaks at Ojai','Ojai, CA','Beautiful Ojai, California sets the stage for wellness for guests of The Oaks at Ojai. Casual and welcoming, stays at this all-inclusive wellness retreat include accommodation, 15 optional daily fitness activities (think yoga, hiking, pilates, boot camp or belly dancing), three daily meals, evening programs and access to the resort''s fitness equipment, pool, sauna and hot tubs.',1,NULL,NULL,NULL,NULL,1,0,0,0,1,1,0,0,0,0,399,2999,2,'http://www.10best.com/awards/travel/best-health-wellness-resort-2016/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (3,'TRM','The Ranch Malibu','Malibu, CA','The Ranch Malibu, an intensive one-week luxury boot camp, eliminates "decision fatigue" with a no-option daily fitness routine featuring group hiking, yoga, weight training and ab work, all amid spectacular hills above the Pacific Ocean. Healthy meals prepared with fresh, organic ingredients exclude processed sugars, alcohol and caffeine.',5,NULL,NULL,NULL,NULL,1,0,0,0,1,1,0,0,0,0,259,799,3,'http://www.10best.com/awards/travel/best-health-wellness-resort-2016/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (4,'RMR','Red Mountain Resort','Ivins, Utah','Fitting for its Utah location, Red Mountain Resort specializes in what it calls "Adventure Vacations." Surrounded by red rock cliffs and canyons, guests enjoy three healthy meals per day, as well as guided activities, like hiking, yoga and fitness classes. Part- and full-day excursions equip guests to actively explore the nearby national parks.',4,NULL,NULL,NULL,NULL,1,0,0,0,0,1,0,0,0,0,299,999,4,'http://www.10best.com/awards/travel/best-health-wellness-resort-2016/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (5,'LASR','Lake Austin Spa Resort','Austin, TX','Lake Austin Spa Resort is an award-winning destination spa tucked away in the beautiful Texas Hill Country, offering more than 100 treatments alongside luxurious accommodations, gourmet meals, a variety of fitness activities and special programs. Many of the thoughtfully-appointed guest rooms have been completely updated, and dogs are allowed in the cottages. Rates include three gourmet meals daily and a variety of fitness activities and daily events, from yoga and paddle boarding to culinary classes and life skills workshops.',3,NULL,NULL,NULL,1,1,0,0,0,0,1,0,0,0,0,359,1299,5,'http://www.10best.com/awards/travel/best-health-wellness-resort-2016/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (6,'HHH','Hilton Head Health','Hilton Head Island, SC','"Eat right. Move more. Less Stress." Those are the pillars supporting the wellness, weight loss and longevity programs at Hilton Head Health on South Carolina''s beautiful Hilton Head Island. True Restaurant serves Mediterranean-style menus during all programs, and visitors can unwind between activities at the Indigo Spa.',2,NULL,NULL,NULL,29,1,0,0,0,0,1,0,0,0,0,379,1399,6,'http://www.10best.com/awards/travel/best-health-wellness-resort-2016/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (7,'OWDW','Orlando-Walt Disney World','Orlando, FL','Entire worlds await your family in Orlando. The Wizarding World of Harry Potter lures Muggles in droves, but the epic Walt Disney World resort still treats kids of all ages to a range of rides and attractions. Parents may find Orlando exhausting, but a Disney trip is a rite of passage for kids. ',NULL,1,NULL,NULL,8,1,1,0,1,1,0,1,0,0,1,199,1450,7,'https://travel.usnews.com/rankings/best-family-vacations/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (8,'ADC','Anaheim Disneyland','Anaheim, CA','This area of Southern California isn''t home to as many amusement parks as its Florida counterpart, but the original Disney resort is still fun for the whole family. Plus, after a day at the theme park it''s just a short drive to the beach. If you plan to travel in the summer, make sure to book your hotel early to secure the best rates.',NULL,2,NULL,NULL,4,1,1,0,1,1,0,1,0,0,1,150,950,8,'https://travel.usnews.com/rankings/best-family-vacations/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (9,'BMS','Branson','Branson, MS','Families travel to this charming Missouri city for its affordability and quirky, themed attractions. Families can transport themselves back to the 19th century at the Silver Dollar City amusement park or tour a life-size replica of the Titanic before cooling off with a dip in Table Rock Lake. ',NULL,9,NULL,NULL,9,0,0,1,1,1,0,1,0,0,1,70,599,9,'https://travel.usnews.com/rankings/best-family-vacations/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (10,'SAUS','Sydney','Sydney, AUS','While the city''s most popular sights may not appeal to the entire family, its kid-friendly attractions will. Darling Harbour alone boasts the Sydney Aquarium and the Australian National Maritime Museum. When temperatures rise, hit Coogee and Bondi beaches. Travel during the shoulder seasons (fall and spring) to avoid the summer crowds. ',NULL,5,NULL,NULL,10,1,1,1,1,1,0,1,0,0,1,325,2500,10,'https://travel.usnews.com/rankings/best-family-vacations/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (11,'SDC','SanDiego','SanDiego, CA','Year-round pleasant temperatures and miles of beaches are just part of the reason families love to vacation in San Diego. The city offers an abundance of outdoor activities and attractions like SeaWorld and the San Diego Zoo, so both kids and adults will be entertained. ',NULL,3,NULL,NULL,5,0,1,0,0,1,0,1,0,0,1,125,899,11,'https://travel.usnews.com/rankings/best-family-vacations/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (12,'GCA','Grand Canyon','Grand Canyon, AZ','The beauty of the Grand Canyon should not be understated, and neither should the many ways to enjoy it. Whether you and the kids raft down the Colorado River or camp near Havasu Falls, your family will never forget the adventures and memories made here',NULL,4,12,NULL,15,0,0,1,1,0,0,1,1,0,1,89,650,12,'https://travel.usnews.com/rankings/best-family-vacations/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (13,'YNPW','Yellowstone National Park','Yellowstone, WY','There''s no replacement for family bonding in a tent or under the stars. When you''re not roasting marshmallows around the fire, your family can spend time at famous sights like the Grand Prismatic Spring and Old Faithful.',NULL,6,13,NULL,16,0,0,1,1,0,0,1,1,0,1,79,600,13,'https://travel.usnews.com/rankings/best-family-vacations/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (14,'WDC','Washington, D.C.','Washington, D.C. ','Families looking to add an educational bent to their vacation should seek out Washington, D.C., for its countless ties to U.S. history. Kids and adults can both enjoy a visit to the Lincoln Memorial or an afternoon spent at the National Zoo. Plus, most major attractions are free to explore and there are a wealth of hotels to choose from.',NULL,7,NULL,NULL,17,0,0,1,0,1,0,1,0,0,1,100,750,14,'https://travel.usnews.com/rankings/best-family-vacations/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (15,'MHI','Maui','Maui, HI','This Hawaiian island offers a little something for each member of the family. Nature enthusiasts can snap photos of the beautiful landscape along the road to Hana, sports lovers can spend the day on the golf course and culture hounds can participate in a traditional luau. You won''t regret splurging on a stay in an oceanfront hotel suite.',NULL,8,NULL,NULL,3,1,0,0,0,1,0,1,0,0,1,300,2500,15,'https://travel.usnews.com/rankings/best-family-vacations/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (16,'SFNSP','Sailing for non-sailors in the Philippines','Philippines','A chance to hoist the main sail and set out to sea on an adventure designed to turn landlubbers into salty seadogs, this trip involves sailing a skippered "paraw" trimaran around uninhabited islands near Borocay in the Philippines. Intrepid travelers are given daily challenges to complete, with the aim of learning seagoing skills and meeting local people. This jaunt is the ultimate sailing trip for non-sailors.',NULL,NULL,1,NULL,18,0,0,0,0,0,0,0,1,0,1,500,3500,16,'https://www.cnn.com/travel/article/best-adventure-vacations-2018/index.html');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (17,'MDHR','Mongol Derby -- the toughest horse race in the world','Mongolia','A 1,000-kilometer course through some of the most remote country in the world, the Mongol Derby offers a challenge for those who have plenty of vacation and a serious dose of gumption to boot. Recreating Genghis Khan''s horse messenger system, experienced riders will travel up to 160 kilometers a day, herding horses between 25 traditional morin urtuus (horse stations). A huge support team of medics and veterinarians is on hand throughout.',NULL,NULL,5,NULL,19,0,0,0,1,0,0,0,1,0,1,550,3850,17,'https://www.cnn.com/travel/article/best-adventure-vacations-2018/index.html');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (18,'SWSM','Swimming with whale sharks in the Maldives','Maldive''s South Ari Atoll','Whale sharks are abundant just off the Maldives'' South Ari Atoll. Local experts lead expeditions from the Mirihi Island Resort on a 55-foot wooden yacht, with the opportunity to strap on a mask and snorkel and swim alongside the largest fish in the world. These gentle giants are often surrounded by other fish and sea creatures looking for protection from predators, making entering the water with them a truly stunning spectacle.',NULL,NULL,8,NULL,20,0,0,0,0,0,0,0,1,0,1,450,3150,18,'https://www.cnn.com/travel/article/best-adventure-vacations-2018/index.html');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (19,'CMFK','Cycling from Mount Fuji to Kyoto','NULL','Rather than zipping straight to Kyoto from Tokyo in a matter of hours on the shinkansen high-speed train, intrepid travelers can saddle up and take the slow road on this 12-day trip. Following an e-bike tour of Tokyo, things take a more strenuous turn on a ride around Fuji Five Lakes, with Japan''s most iconic mountain as a backdrop.The route also takes in traditional villages near Lake Biwa, before ending in the ancient capital of Kyoto, with its abundance of peaceful temples and traditional ryokan, or inns.',NULL,NULL,9,NULL,21,0,0,1,0,0,0,0,1,0,1,600,4200,19,'https://www.cnn.com/travel/article/best-adventure-vacations-2018/index.html');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (20,'KPFA','Kayaking and piranha fishing in the distant Amazon','NULL','Traveling in a dugout canoe through some of the most remote parts of the Amazon in Colombia, Peru and Brazil, this trip is not for the faint of heart. Bedding down in the middle of the jungle, there''s the opportunity to fish for piranhas, meet indigenous tribes and trek through the forest at night, when the wildlife is at its most vociferous.',NULL,NULL,6,NULL,22,0,0,1,1,0,0,0,1,0,1,1000,6000,20,'https://www.cnn.com/travel/article/best-adventure-vacations-2018/index.html');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (21,'TTCSL','A 1,000km tuk-tuk challenge across Sri Lanka','NULL','On this 10-day trip teams of travelers are challenged to find local hotspots and glean information from locals, all in the name of friendly competition. Covering a massive 1,000 kilometers in notoriously unreliable tuk-tuks makes things more interesting.Support teams are on hand throughout, while there''s a chance of encountering local wildlife, including elephants. A portion of the trip''s cost is donated to local charities.',NULL,NULL,11,NULL,6,0,0,1,1,0,0,0,1,0,1,999,5999,21,'https://www.cnn.com/travel/article/best-adventure-vacations-2018/index.html');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (22,'IRMBLB','The Ice Run: Motor biking across frozen Lake Baikal','NULL','With a Russian motorbike and sidecar for transport, the Ice Run is a dream trip for adventure fiends. Starting and finishing in Irkutsk, this challenging ride follows remote forest tracks and long routes over the snowy, open steppe, before taking to the icy expanse of Lake Baikal, the deepest lake in the world. 4x4 support vehicles are on hand, as is GPS to help find essential stops for food and fuel. There are classes on ice riding and motorcycle maintenance before the trip sets out.',NULL,NULL,7,NULL,11,0,0,0,0,0,0,0,1,0,1,1599,7999,22,'https://www.cnn.com/travel/article/best-adventure-vacations-2018/index.html');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (23,'GWN','Glacier walking in Norway','Norway','Adventure company Flash Pack''s singles trips put together like-minded individuals on exciting jaunts, with the chance to meet fellow travelers before hitting the road.Its Norway adventure requires some stamina, with guests strapping on crampons and wielding ice axes for a hike across the vast Haugabreen glacier. Nerves settled, there''s then the chance to go sea kayaking among towering fjords and hike through the spectacular Jostedalsbreen National Park.',NULL,NULL,10,NULL,12,0,0,1,0,0,0,0,1,0,1,899,4500,23,'https://www.cnn.com/travel/article/best-adventure-vacations-2018/index.html');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (24,'CDT','Cave diving in Tuscany','Tuscany, Italy','A luxury Tuscan villa might not seem the most obvious place for adrenaline junkies to find their fix. But then Grotta Giusti isn''t your average luxury Tuscan villa. Beneath its stunning rooms is an underground thermal hot spring lake, where guests can try cave diving. After clambering down a cleft in the rock, instructors lead adventurers through crystal-clear water, past stalagmites and stalactites via a network of labyrinthine tunnels to a series of large caves.',NULL,NULL,3,NULL,13,0,0,1,0,0,0,0,1,0,1,1999,9599,24,'https://www.cnn.com/travel/article/best-adventure-vacations-2018/index.html');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (25,'RTN','Rhino trekking in Namibia','NULL','Setting off before sunrise in 4x4s from Namibia''s remote Desert Rhino Camp, this trek takes searching for endangered rhinos to another level. With experts from Save The Rhinos, travelers can join trackers on foot to get up close to these majestic creatures once they''ve been located. ',NULL,NULL,4,NULL,14,0,0,0,1,0,0,0,1,0,1,2500,9000,25,'https://www.cnn.com/travel/article/best-adventure-vacations-2018/index.html');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (26,'HECR','Heli-exploring the Canadian Rockies','NULL','A week-long adventure in the Canadian Rockies is likely to be many outdoor types'' idea of a dream vacation. Throw in a private helicopter to allow access to some of the range''s most remote passes, meadows and peaks and it''s hard to imagine a better break. After two days spent acclimatizing in Banff National Park, the chopper takes travelers into the high country of the Purcell Mountains for a 72-hour adventure, with experts leading hikes across snow fields and valleys.',NULL,NULL,2,NULL,23,0,0,1,1,0,0,0,1,0,1,2500,5000,26,'https://www.cnn.com/travel/article/best-adventure-vacations-2018/index.html');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (27,'RSSC','Regent Seven Seas Cruises','Mediteranean','Regent Seven Seas is arguably the most inclusive of the biggest luxury brands. Its fares include all-suite accommodations (98 percent come with balconies), meals in main and specialty dining venues, pre- and post-cruise tours and hotel stays, gratuities, shore excursions and beverages from liquor to sodas (in your suite, at dinner or in the ships'' public areas). The ships are on the larger size for luxury, carrying 490 to 750 passengers each -- small enough to create a social onboard atmosphere without the crowds of a big ship, but large enough to offer spacious cabins (the smallest is 301 square feet) and enough dining and entertainment venues to prevent boredom. Luxury touches abound, whether it be a butler in your penthouse suite or exclusive premium bath amenities designed by the L''Occitane line. The 750-passenger Seven Seas Explorer has over-the-top suites and the highest staff-to-passenger ratios in the industry. Wherever in the world you choose to sail, you will be truly pampered. ',NULL,NULL,NULL,6,24,1,0,0,0,1,0,0,0,1,1,2000,5000,27,'https://www.cruisecritic.com/articles.cfm?ID=129 or https://www.rssc.com/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (28,'LCM','Laos Cruise','Laos Mekong',' This relatively small country is the next big thing in Asia river cruising. Touching Vietnam, Cambodia, Thailand, Myanmar (Burma) and the southern tip of China, Laos is at the epicenter of Southeast Asia. Its capital, Vientiane, is located along the Mekong River and showcases French colonial architecture alongside revered Buddhist temples and relics. Most riverboats call nearly 200 miles north in Luang Prabang, a UNESCO World Heritage Site, which offers natural caves, waterfalls and shrines.Pandaw River Cruises offers itineraries in Laos and on the Upper Mekong, with 10-night sailings upstream or downstream. The line will add Sabei Pandaw, its third ship in the region, in November 2018. Avalon Waterways also offers Cambodia/Vietnam cruises that end in Luang Prabang.',NULL,NULL,NULL,1,30,1,0,1,0,1,0,0,0,1,1,4500,9000,28,'https://www.cruisecritic.com/articles.cfm?ID=129 and https://www.pandaw.com/expeditions/laos-mekong/');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (29,'GBA','Glacier Bay','Glacier Bay, Alaska','A destination eons in the making, Glacier Bay�s pristine landscape makes it one of the top spots on an Alaska traveler�s must-see list. Your Glacier Bay cruise takes you through this protected national park spread across 3.2 million acres of southeast Alaska� home to 15 active glaciers, countless seabirds, otters and humpback whales. And a Carnival Alaska cruise is the best way to get right in the middle of it! Your experience begins with complimentary maps to help get the most out of the day�s sightseeing. Then we invite local park rangers to board the ship, narrate your journey and point out the best sights along the way, throughout the day. Carnival Cruise Lines',NULL,NULL,NULL,7,7,1,0,1,0,1,0,0,0,1,1,1500,3500,29,'https://www.carnival.com/cruise-to/alaska-cruises/glacier-bay-cruises.aspx');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (30,'MIV','Mystery Island','Mystery Island, Vanuatu','This tiny, uninhabited inlet, originally named Inyeug, is located at the southernmost end of the Vanuatu archipelago approximately half a mile from the mainland, Aneityum Island. Used during World War II as an airstrip for the allied forces, it was dubbed "Mystery Island" because its location prevented the Japanese from seeing it from the water, making the appearance of allied planes a "mystery." With its white-sand beaches, swaying palm trees and spectacularly clear waters, Mystery Island still holds the allure of a secret oasis. You are greeted upon arrival by live music wafting through the air and a colorful marketplace with rows of stalls selling everything from handicrafts to local treats to hair-braiding services. For the adventurous, aquatic activities, snorkeling, kayaking and stand-up paddleboards beckon, while a glass-bottom boat offers a more sedate and drier way to enjoy the Technicolor marvel of the surrounding coral reef. Round out your visit with a trip to a nearby cultural village to learn more about the traditions and customs of island life.  Princess Cruises',NULL,NULL,NULL,8,26,1,0,1,0,1,0,0,NULL,1,1,1000,5000,30,'https://www.princess.com/excursion/exlistfordestination.do?portid=MY2&exType=S&t=I');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (31,'SPR','St. Petersburg','St. Petersburg, Russia','Founded by the Russian Tsar, Peter the Great, St. Petersburg has for centuries been the cultural center of Russia, with its spectacular architecture, Tchaikovsky operas and the famous Kirov ballet. It has undergone many changes over the decades, but �The Venice of the North� remains a dazzling cruise destination, a Russian city with a European flair, a city with more than 200 museums, and one of the largest English gardens in Europe! Norwegian',NULL,NULL,NULL,2,27,1,0,1,0,1,0,0,0,1,1,2500,9500,31,'https://www.ncl.com/port-of-call/cruises-to-st-petersburg');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (32,'SMN','St. Maarten','St. MAARTEN, NA','Explore two colorful nations on one exotic island on one vacation. Split down the middle centuries ago by two European powers, this 37-mile isle offers cosmopolitan culture, international shopping, and world-class cuisine with a laid-back Caribbean atmosphere. Cruise to St. Maarten and you�ll find the island�s natural attributes are equally fine: the rugged coastline shelters silky crescents of sand framed by green undulating hills. Enjoy the laidback vibe of the beach or put on your hiking shoes and explore ruins of historic forts. One thing�s for sure � when you cruise to St. Maarten you�ll come home with amazing memories that will last a lifetime. Carnival',NULL,9,NULL,10,28,1,0,1,0,1,0,1,0,1,1,1500,4500,32,'https://www.carnival.com/cruise-to/caribbean-cruises/st-maarten-cruises.aspx');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (33,'BKC','Bonaire','Bonaire, Kralenduk','You''ll definitely want to see Sorobon Beach, on the east side of Bonaire located within a large protected bay. Enjoy sunbathing or windsurfing, which has become quite popular in Sorobon Beach thanks to the warm shallow water, steady trade winds and abundance of sunshine. Sorobon Beach has hosted both local and international windsurfing competitions. Also a must-see are Bonaire''s famous pink flamingos which, in mating season, number in the 15,000s. Royal Carribean',NULL,NULL,NULL,9,25,1,0,0,0,1,0,0,0,1,1,1500,4500,33,'http://www.royalcaribbean.com/findacruise/ports/group/home.do?portCode=BON');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (34,'CMC','Cozumel','Cozumel, Mexico','Mayan myth claims that Cozumel was home to the gods. Truly Cozumel is a place fit for the gods, with its dazzling white-sand beaches, ruined Mayan temples, exotic jungle wildlife, and crystalline waters teeming with tropical fish. Just offshore lay Palancar Reef, considered one of the most spectacular coral formations in all the Caribbean. Of course, the gods weren''t the only individuals attracted to this terrestrial paradise: during its long and colorful history, Cozumel has been home to pirates, buccaneers, and freebooters, including Sir Henry Morgan and Jean Lafitte. Today''s traveler will discover the same ravishing beauty and relaxation that entertained gods and pirates alike.  Princess',NULL,NULL,NULL,3,2,1,0,1,0,1,0,0,0,1,1,1755,3555,34,'https://www.princess.com/excursion/exlistfordestination.do?portid=CZM&exType=S&t=C');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (35,'AHC','Amsterdam','Amsterdam, Holland','Life in Amsterdam is centered on its many canals. So the best way to see the city is aboard a glass-topped canal boat, gliding through the town center. Discover the elegant merchant mansions and rows of waterside warehouses, which once housed the riches brought from the Far East. Look for the 17th-century "Skinny Bridge" and Amsterdam''s narrowest house as you make your way past beautiful old churches to the Anne Frank House. Journey by the Jordaan, the old French Quarter that is now a popular artists'' haunt with a wide assortment of caf�s, antique shops, boutiques and galleries. Visit the world''s largest flower auction in the city of Aalsmeer. Visit a Delft Blue Pottery factory to observe the fascinating process of transforming a shapeless piece of clay into a beautiful work of art. Then tour the Hague, seat of government for all the Netherlands. Head out to the countryside to see the quaint windmills in the authentic old village of Zaanse Schans. Stop by the Rembrandt House, home to Rembrandt from 1639 to 1660. Inside is a collection of his engravings and drawings, as well as some of his personal belongings.',NULL,NULL,NULL,5,NULL,1,0,1,0,1,0,0,0,1,1,2599,5999,35,'http://www.royalcaribbean.com/findacruise/ports/group/home.do?portCode=AMS');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (36,'VIC','Venice','Venice, Italy','Rising from the waters of the Laguna Veneta, Venice has long - and rightly - been regarded as one of the world''s most beautiful cities. Napoleon, who had an eye for acquisitions, once described St. Mark''s Square as the finest drawing room in Europe. Certainly, no other site can quite match its superb campanile, Doge''s Palace and recumbent lions. Just over two miles in length, the Grand Canal is lined with stunning buildings that reflect the city''s unique heritage. Cruise through its winding canals on a gondola or watch the bronze Moors on the clock tower strike the passing hours as they have for 500 years - Venice is an unparalleled experience. The city began life as a refuge from barbarian invasions. By the Crusades, Venice''s dominion extended throughout the Adriatic and Mediterranean. The winged lion - symbol of St. Mark - flew over palaces and fortresses from Gibraltar to the Black Sea.  (Princess)',NULL,10,NULL,4,NULL,1,0,1,0,1,0,NULL,0,1,1,3500,8500,36,'https://www.princess.com/excursion/exlistfordestination.do?portid=VCE&exType=S&t=E');
