-- Script Date: 4/8/2018 3:53 PM  - ErikEJ.SqlCeScripting version 3.5.2.75
SELECT [Id]
      ,[Code]
      ,[Destination]
      ,[Location]
      ,[Description]
      ,[HWRank]
      ,[FamRank]
      ,[AdvRank]
      ,[CruRank]
      ,[WedRank]
      ,[SPA]
      ,[AMUSEMENT]
      ,[HISTORY]
      ,[CAMPING]
      ,[ENTERTAINMENT]
      ,[HealthWell]
      ,[Family]
      ,[Adventure]
      ,[Cruise]
      ,[Wedding]
      ,[Price]
      ,[HighPrice]
      ,[DestId]
      ,[Link]
  FROM [Packages];
