-- Script Date: 4/8/2018 2:20 PM  - ErikEJ.SqlCeScripting version 3.5.2.75
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (30,'MIV','Mystery Island','Mystery Island, Vanuatu','This tiny, uninhabited inlet, originally named Inyeug, is located at the southernmost end of the Vanuatu archipelago approximately half a mile from the mainland, Aneityum Island. Used during World War II as an airstrip for the allied forces, it was dubbed Mystery Island because its location prevented the Japanese from seeing it from the water, making the appearance of allied planes a mystery. With its white sand beaches, swaying palm trees and spectacularly clear waters, Mystery Island still holds the allure of a secret oasis. For the adventurous, aquatic activities, snorkeling, kayaking ,stand-up paddleboards, and a glass bottom boat offer various way to enjoy the surrounding coral reef. Princess Cruises.',NULL,NULL,NULL,8,26,1,0,1,0,1,0,0,1,1,1,1000,5000,30,'https://www.princess.com/excursion/exlistfordestination.do?portid=MY2&exType=S&t=I');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (31,'SPR','St. Petersburg','St. Petersburg, Russia','Founded by the Russian Tsar, Peter the Great, St. Petersburg has for centuries been the cultural center of Russia, with its spectacular architecture, Tchaikovsky operas and the famous Kirov ballet. It has undergone many changes over the decades, but �The Venice of the North� remains a dazzling cruise destination, a Russian city with a European flair, a city with more than 200 museums, and one of the largest English gardens in Europe. Norwegian Cruise Line. ',NULL,NULL,NULL,2,27,1,0,1,0,1,0,0,0,1,1,2500,9500,31,'https://www.ncl.com/port-of-call/cruises-to-st-petersburg');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (32,'SMN','St. Maarten','St. MAARTEN, NA','Explore two colorful nations on one exotic island on one vacation. Split down the middle centuries ago by two European powers, this 37-mile isle offers cosmopolitan culture, international shopping, and world-class cuisine with a laid-back Caribbean atmosphere. Cruise to St. Maarten and you�ll find the island�s natural attributes are equally fine: the rugged coastline shelters silky crescents of sand framed by green undulating hills. Enjoy the laidback vibe of the beach or put on your hiking shoes and explore ruins of historic forts. One thing�s for sure, when you cruise to St. Maarten you will come home with amazing memories that will last a lifetime. Carnival',NULL,9,NULL,10,28,1,0,1,0,1,0,1,0,1,1,1500,4500,32,'https://www.carnival.com/cruise-to/caribbean-cruises/st-maarten-cruises.aspx');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (33,'BKC','Bonaire','Bonaire, Kralenduk','You''ll definitely want to see Sorobon Beach, on the east side of Bonaire located within a large protected bay. Enjoy sunbathing or windsurfing, which has become quite popular in Sorobon Beach thanks to the warm shallow water, steady trade winds and abundance of sunshine. Sorobon Beach has hosted both local and international windsurfing competitions. Also a must-see are Bonaire''s famous pink flamingos which, in mating season, number in the 15,000s. Royal Carribean',NULL,NULL,NULL,9,25,1,0,0,0,1,0,0,0,1,1,1500,4500,33,'http://www.royalcaribbean.com/findacruise/ports/group/home.do?portCode=BON');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (34,'CMC','Cozumel','Cozumel, Mexico','Mayan myth claims that Cozumel was home to the gods. Truly Cozumel is a place fit for the gods, with its dazzling white-sand beaches, ruined Mayan temples, exotic jungle wildlife, and crystalline waters teeming with tropical fish. Just offshore lay Palancar Reef, considered one of the most spectacular coral formations in all the Caribbean. Of course, the gods weren''t the only individuals attracted to this terrestrial paradise: during its long and colorful history, Cozumel has been home to pirates, buccaneers, and freebooters, including Sir Henry Morgan and Jean Lafitte. Today''s traveler will discover the same ravishing beauty and relaxation that entertained gods and pirates alike.  Princess',NULL,NULL,NULL,3,2,1,0,1,0,1,0,0,0,1,1,1755,3555,34,'https://www.princess.com/excursion/exlistfordestination.do?portid=CZM&exType=S&t=C');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (35,'AHC','Amsterdam','Amsterdam, Holland','Life in Amsterdam is centered on its many canals. So the best way to see the city is aboard a glass-topped canal boat, gliding through the town center. Discover the elegant merchant mansions and rows of waterside warehouses, which once housed the riches brought from the Far East. Look for the 17th-century "Skinny Bridge" and Amsterdam''s narrowest house as you make your way past beautiful old churches to the Anne Frank House. Journey by the Jordaan, the old French Quarter that is now a popular artists'' haunt with a wide assortment of caf�s, antique shops, boutiques and galleries. Visit the world''s largest flower auction in the city of Aalsmeer, and more.',NULL,NULL,NULL,5,NULL,1,0,1,0,1,0,0,0,1,1,2599,5999,35,'http://www.royalcaribbean.com/findacruise/ports/group/home.do?portCode=AMS');
INSERT INTO [Packages] ([Id],[Code],[Destination],[Location],[Description],[HWRank],[FamRank],[AdvRank],[CruRank],[WedRank],[SPA],[AMUSEMENT],[HISTORY],[CAMPING],[ENTERTAINMENT],[HealthWell],[Family],[Adventure],[Cruise],[Wedding],[Price],[HighPrice],[DestId],[Link]) 
VALUES (36,'VIC','Venice','Venice, Italy','Rising from the waters of the Laguna Veneta, Venice has long - and rightly - been regarded as one of the world''s most beautiful cities. Napoleon, who had an eye for acquisitions, once described St. Mark''s Square as the finest drawing room in Europe. Certainly, no other site can quite match its superb campanile, Doge''s Palace and recumbent lions. Just over two miles in length, the Grand Canal is lined with stunning buildings that reflect the city''s unique heritage. Cruise through its winding canals on a gondola or watch the bronze Moors on the clock tower strike the passing hours as they have for 500 years - Venice is an unparalleled experience.  (Princess)',NULL,10,NULL,4,NULL,1,0,1,0,1,0,1,0,1,1,3500,8500,36,'https://www.princess.com/excursion/exlistfordestination.do?portid=VCE&exType=S&t=E');
