CREATE TABLE [dbo].[UserInfo]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FirstName] VARCHAR(50) NOT NULL DEFAULT NULL, 
    [LastName] VARCHAR(50) NOT NULL DEFAULT NULL, 
    [UserId] VARCHAR(50) NOT NULL DEFAULT NULL, 
    [Password] VARCHAR(50) NOT NULL DEFAULT NULL
)
